name: Hello World

on:
    workflow_dispatch:

jobs:
    hello-world:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v4

        - name: Say Hello
          run: ./hello-world.ps1