name: PowerShell Example

on:
    workflow_call:
      secrets:
        github_pat:
          required: true

jobs:
  ps-job:
    runs-on: windows-latest
    steps:
      - name: Say Hello
        run: |
          Write-Host "Hello from PowerShell"
          
      - name: Get Public Repos
        run: |
          $Uri = "https://api.github.com/users/leebuhrmann/repos"
          $Headers = @{
              "Accept" = "application/vnd.github+json"
              "Authorization"="Bearer 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"
              "X-GitHub-Api-Version"="2022-11-28"
          }
          $Response = Invoke-RestMethod -Uri $Uri -Headers $Headers -Method Get
          $response | Select-Object name, description | Format-Table